<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'name', 'is_directory', 'level', 'path'
    ];

    /**
     * @var array
     */
    protected $casts = [
        'is_directory'  =>  'boolean',
    ];

    /**
     * 监听自动创建生成数据
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        //监听Category的创建事件,用于初始化path和level字段值
        static::creating(function(Category $category){
            //如果创建的是一个根类目录
            if (is_null($category->parent_id)){
                //将层级设为0
                $category->level=0;
                //将path设为-
                $category->path = '-';
            }else{
                //将层级设为父类的目层级+1
                $category->level = $category->parent->level+1;
                //将path值设为父类目的path追加父类目id以及最后跟上一个'-'符号
                $category->path = $category->parent->path.$category->parent_id.'-';
            }
        });
    }

    /**
     * 获取父级类目
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * 获取子类目
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany(Category::class,'parent_id');
    }

    /**
     * 返回所有父级目录id
     * 定一个一个访问器，获取所有祖先类目的 ID 值
     * @return array
     */
    public function getPathIdsAttribute()
    {
        // trim($str, '-') 将字符串两端的 - 符号去除
        // explode() 将字符串以 - 为分隔切割为数组
        // 最后 array_filter 将数组中的空值移除
        return array_filter(explode('-', trim($this->path, '-')));
    }

    /**
     * 获取所有祖先类目并按层级排序
     * @return \Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    public function getAncestorsAttribute()
    {
        return Category::query()
            // 使用上面的访问器获取所有祖先类目 ID
            ->whereIn('id', $this->path_ids)
            // 按层级排序
            ->orderBy('level')
            ->get();
    }

    /**
     * 定义一个访问器，获取以 - 为分隔的所有祖先类目名称以及当前类目的名称
     * @return mixed
     */
    public function getFullNmaeAttribute()
    {
        return $this->ancestors // 获取所有祖先类目
            ->pluck('name')// 取出所有祖先类目的 name 字段作为一个数组
            ->push($this->name)// 将当前类目的 name 字段值加到数组的末尾
            ->implode('-');// 用 - 符号将数组的值组装成一个字符串
    }

}
